// content.js
module.exports = [
  "Week 1: Welcome. Start by understanding your own communication style and how you naturally express interest without forcing anything.",
  "Week 2: Pay attention to how you listen. Attraction grows faster when people feel genuinely heard, not impressed.",
  "Week 3: Practice relaxed conversations with no goal other than enjoying the interaction.",
  "Week 4: Challenge week: initiate at least one conversation you would normally overthink.",
  "Week 5: Learn to read basic signals of interest versus politeness.",
  "Week 6: Focus on clarity—say what you mean without overexplaining.",
  "Week 7: Improve body language: eye contact, posture, and calm presence.",
  "Week 8: Learn to manage nervous energy instead of trying to hide it.",
  "Week 9: Practice playful tone without seeking validation.",
  "Week 10: Understand that attraction grows through consistency, not intensity.",

  "Week 11: Reflect on what makes you feel confident in conversations.",
  "Week 12: Learn how humor works best when it’s natural, not forced.",
  "Week 13: Control week—less talking, more observing reactions.",
  "Week 14: Practice asking better questions instead of trying to impress.",
  "Week 15: Learn the difference between interest and attachment.",
  "Week 16: Build comfort through emotional stability, not constant attention.",
  "Week 17: Develop patience—rushing kills attraction.",
  "Week 18: Improve your emotional awareness and boundaries.",
  "Week 19: Learn to recover smoothly from awkward moments.",
  "Week 20: Two-month review—notice growth in confidence and clarity.",

  "Week 21: Practice initiating plans instead of waiting.",
  "Week 22: Learn how to express interest without pressure.",
  "Week 23: Focus on tone and timing in messages.",
  "Week 24: Take breaks from overthinking and trust your instincts.",
  "Week 25: Challenge week—no second-guessing texts after sending.",
  "Week 26: You now communicate more naturally than before.",
  "Week 27: Learn how attraction builds through shared experiences.",
  "Week 28: Practice balancing availability and independence.",
  "Week 29: Identify patterns that push people away and correct them.",
  "Week 30: Learn emotional control when expectations appear.",

  "Week 31: Improve confidence by staying grounded during silence.",
  "Week 32: Learn to let conversations breathe without filling every gap.",
  "Week 33: Understand emotional pacing in early attraction.",
  "Week 34: Work on expressing appreciation authentically.",
  "Week 35: Recovery week—reflect instead of forcing progress.",
  "Week 36: Learn how attraction changes over time.",
  "Week 37: Strengthen self-respect through boundaries.",
  "Week 38: Practice being present instead of performing.",
  "Week 39: Learn to stay calm when things feel uncertain.",
  "Week 40: Four-month review—confidence should feel natural now.",

  "Week 41: Practice leading interactions calmly.",
  "Week 42: Learn to recognize emotional availability.",
  "Week 43: Strengthen emotional resilience.",
  "Week 44: Learn how attraction responds to authenticity.",
  "Week 45: Adapt communication styles to different personalities.",
  "Week 46: Learn to express needs clearly.",
  "Week 47: Emotional recovery and reset.",
  "Week 48: Combine confidence with empathy.",
  "Week 49: Master emotional pacing in conversations.",
  "Week 50: Half-year reflection—notice your growth.",

  "Week 51: Define your personal attraction style.",
  "Week 52: Learn from past interactions without judgment.",
  "Week 53: Practice emotional consistency.",
  "Week 54: Learn to stay grounded under emotional pressure.",
  "Week 55: Develop a calm, attractive mindset.",
  "Week 56: Improve communication during conflict.",
  "Week 57: Practice balance between interest and independence.",
  "Week 58: Learn to adapt without losing yourself.",
  "Week 59: Strategic emotional rest.",
  "Week 60: Six-month progress evaluation.",

  "Week 61: Enter a confident communication phase.",
  "Week 62: Practice clarity under emotional tension.",
  "Week 63: Master rhythm and flow in conversations.",
  "Week 64: Focus training—be present, not distracted.",
  "Week 65: Build emotional strength through self-trust.",
  "Week 66: Practice intentional dating decisions.",
  "Week 67: Emotional reset and clarity.",
  "Week 68: Precision in words and actions.",
  "Week 69: Calm confidence in uncertainty.",
  "Week 70: Long-term attraction review.",

  "Week 71: Learn patience in deeper connections.",
  "Week 72: Your style is now clearly defined.",
  "Week 73: Near-effortless communication.",
  "Week 74: Psychological attraction awareness.",
  "Week 75: Maintain steady emotional presence.",
  "Week 76: Intelligent emotional recovery.",
  "Week 77: Fast adaptation without overthinking.",
  "Week 78: Decisive emotional leadership.",
  "Week 79: Calm, focused mindset.",
  "Week 80: Advanced connection review.",

  "Week 81: Advanced emotional intelligence phase.",
  "Week 82: Full confidence in interactions.",
  "Week 83: Eliminate emotional overreactions.",
  "Week 84: Confidence combined with warmth.",
  "Week 85: Trust the process.",
  "Week 86: High-level communication awareness.",
  "Week 87: Emotional recovery mastery.",
  "Week 88: Clarity and self-assurance.",
  "Week 89: Consistency in who you are.",
  "Week 90: Long-term evaluation.",

  "Week 91: No shortcuts—stay authentic.",
  "Week 92: Final refinements in communication.",
  "Week 93: Mind and emotions aligned.",
  "Week 94: Total emotional confidence.",
  "Week 95: Strong self-respect.",
  "Week 96: Calm maturity.",
  "Week 97: Final growth push.",
  "Week 98: Peak emotional discipline.",
  "Week 99: Ultimate readiness for healthy connection.",
  "Week 100: CONGRATULATIONS! You now communicate with confidence, clarity, and emotional intelligence."
];

